### ISSUE TITLE
Manually inspect projects in poor, medium, and good health.

### ISSUE THREAD

**Issue by shawnohare** [140proof/OSS-health#7]
We need to inspect projects in various states of health in order to get an idea of how to appropriately score certain unbound parameters.  For example

- How many stars warrant a letter grade of C, B, or A for this category?
- How many followers warrant a letter grade of C, B, A for this category?

**Comment by shawnohare** [comment]
Create a table.

**Comment by shawnohare** [comment]
I'm happy to dig through some projects, but as a first step we should populate these categories with some examples.

Ya'll seem a bit more familiar with projects that were initiallly promising but then died.  These are the ones I'm particularly interested in looking at, because without really knowing the dev history it can be difficult for a n00b to determine the health of a project.   By n00b I mean dudes who read math journals on a regular basis.

The Induction project comes to mind.  When I initially stumbled upon the project I thought it seemed quite nice, but @ahamidi and @mhfs essentially told me it was dead.

cc @jonhatalla @jhardin293

**Comment by jhardin293** [comment]
Link to Doc https://docs.google.com/spreadsheets/d/1AnlgmdEnXIPCAmgkJ8MXIk-7htu5D2hGPin9tPo6fj4/edit#gid=0

**Comment by ahamidi** [comment]
Updated the doc with the obvious stats (stars, forks, issues etc...)
